[2023-04-04 11:36:08,668][root][INFO] - 
Overwritten parameters in the config: 
mode=tiling
[2023-04-04 11:36:08,669][root][INFO] - 
---------------------------------------
Let's start tiling for segmentation !!!
---------------------------------------
[2023-04-04 11:36:08,844][matplotlib][DEBUG] - matplotlib data path: C:\Users\abfernan\.conda\envs\geo_deep_env\lib\site-packages\matplotlib\mpl-data
[2023-04-04 11:36:08,848][matplotlib][DEBUG] - CONFIGDIR=C:\Users\abfernan\.matplotlib
[2023-04-04 11:36:08,850][matplotlib][DEBUG] - interactive is False
[2023-04-04 11:36:08,850][matplotlib][DEBUG] - platform is win32
[2023-04-04 11:36:08,895][matplotlib][DEBUG] - CACHEDIR=C:\Users\abfernan\.matplotlib
[2023-04-04 11:36:08,898][matplotlib.font_manager][DEBUG] - Using fontManager instance from C:\Users\abfernan\.matplotlib\fontlist-v330.json
[2023-04-04 11:36:09,144][fiona.session][DEBUG] - Could not import boto3, continuing with reduced functionality.
[2023-04-04 11:36:09,153][fiona._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:09,154][fiona._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:09,849][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nchpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:12,185][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_gahpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:12,351][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nchpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:12,507][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nchpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:12,589][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_gahpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:12,693][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nchpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:12,812][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_ethpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:12,917][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_mnhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:13,006][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_okhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:13,102][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_kshpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:13,201][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_iahpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:13,325][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/ca_nrc_ABCSRSV4.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:13,417][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nmhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:14,410][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_uthpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:36:14,888][root][ERROR] - The key download_data as a None value.
[2023-04-04 11:36:14,889][root][ERROR] - The key multiprocessing as a None value.
[2023-04-04 11:36:14,890][root][ERROR] - The key write_dest_raster as a None value.
[2023-04-04 11:36:14,890][root][ERROR] - The key clahe_clip_limit as a None value.
[2023-04-04 11:36:15,035][tiling_segmentation][WARNING] - Debug mode activated. Some debug features may mobilize extra disk space and cause delays in execution.
[2023-04-04 11:36:15,036][dataset.aoi][INFO] - 
	Successfully read csv file: rawImg.csv
	Number of rows: 1
	Copying first row:
{'tif': 'C:\\Users\\abfernan\\CrossCanFloodMapping\\RawData\\TestTiling\\ON_VilleGatineau.tif', 'gpkg': 'C:\\Users\\abfernan\\CrossCanFloodMapping\\RawData\\TestTiling\\ON_VilleGatineau.gpkg', 'split': 'trn', 'aoi_id': 'VilleGatineau-1'}

[2023-04-04 11:36:15,067][rasterio.env][DEBUG] - Entering env context: <rasterio.env.Env object at 0x0000020964E4E560>
[2023-04-04 11:36:15,068][rasterio.env][DEBUG] - Starting outermost env
[2023-04-04 11:36:15,069][rasterio.env][DEBUG] - No GDAL environment exists
[2023-04-04 11:36:15,069][rasterio.env][DEBUG] - New GDAL environment <rasterio._env.GDALEnv object at 0x0000020964E4E5C0> created
[2023-04-04 11:36:15,071][rasterio._filepath][DEBUG] - Installing FilePath filesystem handler plugin...
[2023-04-04 11:36:15,071][rasterio._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:15,071][rasterio._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:15,072][rasterio._env][DEBUG] - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x0000020964E4E5C0>.
[2023-04-04 11:36:15,072][rasterio.env][DEBUG] - Entered env context: <rasterio.env.Env object at 0x0000020964E4E560>
[2023-04-04 11:36:15,072][rasterio._base][DEBUG] - Sharing flag: 0
[2023-04-04 11:36:15,089][rasterio._base][DEBUG] - Nodata success: 1, Nodata value: -9999.000000
[2023-04-04 11:36:15,090][rasterio._base][DEBUG] - Dataset <open DatasetReader name='C:/Users/abfernan/CrossCanFloodMapping/RawData/TestTiling/ON_VilleGatineau.tif' mode='r'> is started.
[2023-04-04 11:36:15,090][rasterio.env][DEBUG] - Exiting env context: <rasterio.env.Env object at 0x0000020964E4E560>
[2023-04-04 11:36:15,090][rasterio.env][DEBUG] - Cleared existing <rasterio._env.GDALEnv object at 0x0000020964E4E5C0> options
[2023-04-04 11:36:15,091][rasterio._env][DEBUG] - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x0000020964E4E5C0>.
[2023-04-04 11:36:15,091][rasterio.env][DEBUG] - Exiting outermost env
[2023-04-04 11:36:15,091][rasterio.env][DEBUG] - Exited env context: <rasterio.env.Env object at 0x0000020964E4E560>
[2023-04-04 11:36:15,092][root][DEBUG] - Raster to validate: <open DatasetReader name='C:/Users/abfernan/CrossCanFloodMapping/RawData/TestTiling/ON_VilleGatineau.tif' mode='r'>
Size: 12398070
Extended check: False
[2023-04-04 11:36:15,098][rasterio.env][DEBUG] - Entering env context: <rasterio.env.Env object at 0x0000020964E4E620>
[2023-04-04 11:36:15,099][rasterio.env][DEBUG] - Starting outermost env
[2023-04-04 11:36:15,099][rasterio.env][DEBUG] - No GDAL environment exists
[2023-04-04 11:36:15,099][rasterio.env][DEBUG] - New GDAL environment <rasterio._env.GDALEnv object at 0x0000020964E4E530> created
[2023-04-04 11:36:15,101][rasterio._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:15,101][rasterio._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:15,101][rasterio._env][DEBUG] - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x0000020964E4E530>.
[2023-04-04 11:36:15,102][rasterio.env][DEBUG] - Entered env context: <rasterio.env.Env object at 0x0000020964E4E620>
[2023-04-04 11:36:15,102][rasterio._base][DEBUG] - Sharing flag: 0
[2023-04-04 11:36:15,104][rasterio._base][DEBUG] - Nodata success: 1, Nodata value: -9999.000000
[2023-04-04 11:36:15,105][rasterio._base][DEBUG] - Dataset <open DatasetReader name='C:/Users/abfernan/CrossCanFloodMapping/RawData/TestTiling/ON_VilleGatineau.tif' mode='r'> is started.
[2023-04-04 11:36:15,105][rasterio.env][DEBUG] - Exiting env context: <rasterio.env.Env object at 0x0000020964E4E620>
[2023-04-04 11:36:15,105][rasterio.env][DEBUG] - Cleared existing <rasterio._env.GDALEnv object at 0x0000020964E4E530> options
[2023-04-04 11:36:15,106][rasterio._env][DEBUG] - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x0000020964E4E530>.
[2023-04-04 11:36:15,106][rasterio.env][DEBUG] - Exiting outermost env
[2023-04-04 11:36:15,106][rasterio.env][DEBUG] - Exited env context: <rasterio.env.Env object at 0x0000020964E4E620>
[2023-04-04 11:36:15,107][rasterio.env][DEBUG] - Entering env context: <rasterio.env.Env object at 0x0000020964E4D210>
[2023-04-04 11:36:15,107][rasterio.env][DEBUG] - Starting outermost env
[2023-04-04 11:36:15,107][rasterio.env][DEBUG] - No GDAL environment exists
[2023-04-04 11:36:15,108][rasterio.env][DEBUG] - New GDAL environment <rasterio._env.GDALEnv object at 0x0000020964E4E530> created
[2023-04-04 11:36:15,109][rasterio._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:15,109][rasterio._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:15,110][rasterio._env][DEBUG] - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x0000020964E4E530>.
[2023-04-04 11:36:15,110][rasterio.env][DEBUG] - Entered env context: <rasterio.env.Env object at 0x0000020964E4D210>
[2023-04-04 11:36:15,110][rasterio._base][DEBUG] - Sharing flag: 0
[2023-04-04 11:36:15,112][rasterio._base][DEBUG] - Nodata success: 1, Nodata value: -9999.000000
[2023-04-04 11:36:15,113][rasterio._base][DEBUG] - Dataset <open DatasetReader name='C:/Users/abfernan/CrossCanFloodMapping/RawData/TestTiling/ON_VilleGatineau.tif' mode='r'> is started.
[2023-04-04 11:36:15,113][rasterio.env][DEBUG] - Exiting env context: <rasterio.env.Env object at 0x0000020964E4D210>
[2023-04-04 11:36:15,113][rasterio.env][DEBUG] - Cleared existing <rasterio._env.GDALEnv object at 0x0000020964E4E530> options
[2023-04-04 11:36:15,113][rasterio._env][DEBUG] - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x0000020964E4E530>.
[2023-04-04 11:36:15,114][rasterio.env][DEBUG] - Exiting outermost env
[2023-04-04 11:36:15,114][rasterio.env][DEBUG] - Exited env context: <rasterio.env.Env object at 0x0000020964E4D210>
[2023-04-04 11:36:15,114][root][DEBUG] - Raster to validate: <open DatasetReader name='C:/Users/abfernan/CrossCanFloodMapping/RawData/TestTiling/ON_VilleGatineau.tif' mode='r'>
Size: 12398070
Extended check: False
[2023-04-04 11:36:15,115][rasterio.env][DEBUG] - Entering env context: <rasterio.env.Env object at 0x0000020964E4E740>
[2023-04-04 11:36:15,115][rasterio.env][DEBUG] - Starting outermost env
[2023-04-04 11:36:15,115][rasterio.env][DEBUG] - No GDAL environment exists
[2023-04-04 11:36:15,116][rasterio.env][DEBUG] - New GDAL environment <rasterio._env.GDALEnv object at 0x0000020964E4E590> created
[2023-04-04 11:36:15,117][rasterio._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:15,117][rasterio._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:15,117][rasterio._env][DEBUG] - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x0000020964E4E590>.
[2023-04-04 11:36:15,118][rasterio.env][DEBUG] - Entered env context: <rasterio.env.Env object at 0x0000020964E4E740>
[2023-04-04 11:36:15,118][rasterio._base][DEBUG] - Sharing flag: 0
[2023-04-04 11:36:15,121][rasterio._base][DEBUG] - Nodata success: 1, Nodata value: -9999.000000
[2023-04-04 11:36:15,121][rasterio._base][DEBUG] - Dataset <open DatasetReader name='C:/Users/abfernan/CrossCanFloodMapping/RawData/TestTiling/ON_VilleGatineau.tif' mode='r'> is started.
[2023-04-04 11:36:15,121][rasterio.env][DEBUG] - Exiting env context: <rasterio.env.Env object at 0x0000020964E4E740>
[2023-04-04 11:36:15,122][rasterio.env][DEBUG] - Cleared existing <rasterio._env.GDALEnv object at 0x0000020964E4E590> options
[2023-04-04 11:36:15,122][rasterio._env][DEBUG] - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x0000020964E4E590>.
[2023-04-04 11:36:15,122][rasterio.env][DEBUG] - Exiting outermost env
[2023-04-04 11:36:15,122][rasterio.env][DEBUG] - Exited env context: <rasterio.env.Env object at 0x0000020964E4E740>
[2023-04-04 11:36:15,124][fiona._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:15,124][fiona._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:15,167][fiona._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:15,167][fiona._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:15,168][fiona.ogrext][DEBUG] - Got coordinate system
[2023-04-04 11:36:15,168][fiona.ogrext][DEBUG] - Got coordinate system
[2023-04-04 11:36:15,170][fiona.crs][DEBUG] - Matched. confidence=100, c_code=b'2959', c_name=b'EPSG'
[2023-04-04 11:36:15,170][fiona.ogrext][DEBUG] - OLC_FASTSETNEXTBYINDEX: 0
[2023-04-04 11:36:15,171][fiona.ogrext][DEBUG] - OLC_FASTFEATURECOUNT: 1
[2023-04-04 11:36:15,171][fiona.ogrext][DEBUG] - Next index: 0
[2023-04-04 11:36:15,171][fiona.ogrext][DEBUG] - Next index: 1
[2023-04-04 11:36:15,200][fiona.collection][DEBUG] - Flushed buffer
[2023-04-04 11:36:15,203][fiona.collection][DEBUG] - Stopped session
[2023-04-04 11:36:15,204][fiona._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:15,205][fiona._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:15,212][fiona._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:36:15,213][fiona._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:36:15,213][fiona.ogrext][DEBUG] - Got coordinate system
[2023-04-04 11:36:15,213][fiona.ogrext][DEBUG] - Got coordinate system
[2023-04-04 11:36:15,214][fiona.crs][DEBUG] - Matched. confidence=100, c_code=b'2959', c_name=b'EPSG'
[2023-04-04 11:36:15,214][fiona.ogrext][DEBUG] - OLC_FASTSETNEXTBYINDEX: 0
[2023-04-04 11:36:15,214][fiona.ogrext][DEBUG] - OLC_FASTFEATURECOUNT: 1
[2023-04-04 11:36:15,215][fiona.ogrext][DEBUG] - Next index: 0
[2023-04-04 11:36:15,215][fiona.ogrext][DEBUG] - Next index: 1
[2023-04-04 11:36:15,309][fiona.collection][DEBUG] - Flushed buffer
[2023-04-04 11:36:15,310][fiona.collection][DEBUG] - Stopped session
[2023-04-04 11:36:15,324][rasterio.crs][DEBUG] - Matched. confidence=100, c_code=b'2959', c_name=b'EPSG'
[2023-04-04 11:36:15,343][tiling_segmentation][INFO] - Patches will be written to C:\Users\abfernan\CrossCanFloodMapping\RawData\TestTiling\template_project


[2023-04-04 11:36:15,344][tiling_segmentation][INFO] - Preparing patches 
	Samples_size: 384 
[2023-04-04 11:36:15,345][rasterio._warp][DEBUG] - Exported CRS to WKT.
[2023-04-04 11:36:15,345][rasterio._warp][DEBUG] - Warp_extras: {'init_dest': 'NO_DATA'}
[2023-04-04 11:36:15,360][rasterio._base][DEBUG] - Nodata success: 1, Nodata value: -9999.000000
[2023-04-04 11:36:15,360][rasterio._base][DEBUG] - Dataset <closed WarpedVRT name='WarpedVRT(C:/Users/abfernan/CrossCanFloodMapping/RawData/TestTiling/ON_VilleGatineau.tif)' mode='r'> is started.
[2023-04-04 11:36:15,361][rasterio._io][DEBUG] - Output nodata value read from file: -9999.0
[2023-04-04 11:36:15,362][rasterio._io][DEBUG] - Output nodata values: [-9999.0]
[2023-04-04 11:36:15,363][rasterio._io][DEBUG] - all_valid: False
[2023-04-04 11:36:15,363][rasterio._io][DEBUG] - mask_flags: ([<MaskFlags.nodata: 8>],)
[2023-04-04 11:36:15,363][rasterio._io][DEBUG] - Jump straight to _read()
[2023-04-04 11:36:15,364][rasterio._io][DEBUG] - Window: None
[2023-04-04 11:36:15,364][rasterio._io][DEBUG] - IO window xoff=0.0 yoff=0.0 width=1752.0 height=1766.0
[2023-04-04 11:36:15,490][rasterio.crs][DEBUG] - Matched. confidence=100, c_code=b'2959', c_name=b'EPSG'
