[2023-04-04 11:33:35,919][root][INFO] - 
Overwritten parameters in the config: 
mode=tiling
[2023-04-04 11:33:35,920][root][INFO] - 
---------------------------------------
Let's start tiling for segmentation !!!
---------------------------------------
[2023-04-04 11:33:36,321][matplotlib][DEBUG] - matplotlib data path: C:\Users\abfernan\.conda\envs\geo_deep_env\lib\site-packages\matplotlib\mpl-data
[2023-04-04 11:33:36,325][matplotlib][DEBUG] - CONFIGDIR=C:\Users\abfernan\.matplotlib
[2023-04-04 11:33:36,327][matplotlib][DEBUG] - interactive is False
[2023-04-04 11:33:36,328][matplotlib][DEBUG] - platform is win32
[2023-04-04 11:33:36,378][matplotlib][DEBUG] - CACHEDIR=C:\Users\abfernan\.matplotlib
[2023-04-04 11:33:36,382][matplotlib.font_manager][DEBUG] - Using fontManager instance from C:\Users\abfernan\.matplotlib\fontlist-v330.json
[2023-04-04 11:33:36,703][fiona.session][DEBUG] - Could not import boto3, continuing with reduced functionality.
[2023-04-04 11:33:36,711][fiona._env][DEBUG] - GDAL_DATA found in environment.
[2023-04-04 11:33:36,711][fiona._env][DEBUG] - PROJ_DATA found in environment.
[2023-04-04 11:33:40,141][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nchpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:42,483][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_gahpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:42,604][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_TN.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:42,719][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nchpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:42,874][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nchpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:42,945][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_gahpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:43,273][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nchpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:43,400][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_ethpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:43,494][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_mnhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:43,581][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_okhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:43,698][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_kshpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:43,930][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_iahpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:44,048][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/ca_nrc_ABCSRSV4.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:44,134][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_nmhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:44,241][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_azhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:44,346][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_wyhpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:44,427][pyproj][DEBUG] - PROJ_ERROR: Cannot open https://cdn.proj.org/us_noaa_uthpgn.tif: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
[2023-04-04 11:33:47,180][root][CRITICAL] - Couldn't locate path: C:\Users\abdielfer\RNCanWork\GDLData\TestTiling.
Provided key: raw_data_dir
